spring:
  application:
    name: financial-planner-backend

data:
  mongodb:
    uri: ${MONGO_URI}
    database: finplanner

jwt:
  secret: $JWT_SECRET=super-secret-key-at-least-32-chars
  expiration: 86400000 # 24h
